name = "JuliaOSBackend"
uuid = "12345678-1234-5678-1234-567812345678"
authors = ["JuliaOS Contributors <contributors@juliaos.org>"]
version = "0.1.0"

[deps]

[sources]

[compat]

[extras]

[targets]
