[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "juliaos"
version = "0.1.0"
description = "Python wrapper for JuliaOS Framework"
readme = "README.md"
authors = [
    {name = "JuliaOS Team", email = "info@juliaos.com"}
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
requires-python = ">=3.8"
dependencies = [
    "websockets>=10.0",
    "aiohttp>=3.8.0",
    "pydantic>=1.9.0",
    "asyncio>=3.4.3",
    "python-dotenv>=0.19.0",
    "nest-asyncio>=1.5.5",
    "langchain>=0.0.267",
    "langchain-core>=0.0.10",
    "langchain-community>=0.0.10",
]

[project.optional-dependencies]
llm = [
    "openai>=1.0.0",
    "anthropic>=0.5.0",
    "google-generativeai>=0.3.0",
    "cohere>=4.0.0",
    "replicate>=0.15.0",
]
adk = [
    "google-adk>=0.2.0",
]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.18.0",
    "black>=22.0.0",
    "isort>=5.10.0",
    "mypy>=0.950",
]

[project.urls]
"Homepage" = "https://github.com/juliaos/juliaos"
"Bug Tracker" = "https://github.com/juliaos/juliaos/issues"
